# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

author: Beau Barker
baseurl: "" # the subpath of your site, e.g. /blog
description: > # this means to ignore newlines until "baseurl:"
  ...
email: beauinmelbourne@gmail.com
future: true # Include posts with a date in the future
github_username: bcb
google_analytics: UA-81795603-1
highlighter: rouge
markdown: kramdown
permalink: /:categories/:title
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
repository: bcb/bcb.github.io
social:
  name: Beau Barker
  links:
    - https://twitter.com/bbmelb
    - https://www.linkedin.com/in/beaub
    - https://github.com/bcb
title: Beau Barker
twitter:
  username: bbmelb
url: "https://bcb.github.io" # the base hostname & protocol for your site

collections:
    jsonrpc:
        title: JSON-RPC
        output: true
        priority: 1
        intro: >
            My libraries:
            <a href="https://jsonrpcclient.readthedocs.io">jsonrpcclient</a> and
            <a href="https://jsonrpcserver.readthedocs.io">jsonrpcserver</a>.
    airflow:
        title: Airflow
        output: true
        priority: 2
    graphql:
        title: GraphQL
        output: true
        priority: 3
    micropython:
        title: Micropython
        output: true
        priority: 4
    aws:
        title: Amazon Web Services
        output: true
        priority: 5
