# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
email: beauinmelbourne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcb.github.io" # the base hostname & protocol for your site
author: Beau Barker
twitter_username: bbmelb
github_username: bcb
future: true # Include posts with a date in the future
google_analytics: UA-81795603-1
gems:
    - jekyll-redirect-from

# Build settings
markdown: kramdown
highlighter: rouge

collections:
    jsonrpc:
        title: JSON-RPC
        output: true
        priority: 1
        intro: >
            My python libraries:
            <a href="https://jsonrpcclient.readthedocs.io">jsonrpcclient</a> and
            <a href="https://jsonrpcserver.readthedocs.io">jsonrpcserver</a>.
    aws:
        title: Amazon Web Services
        output: true
        priority: 99
    graphql:
        title: GraphQL
        output: true
        priority: 2
    micropython:
        title: Micropython
        output: true
        priority: 3
